name: ine
favicon: null
layout_spectrum: 0.18073
typography_spectrum: 0.30162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4fee7'
    - '#5e0525'
    - '#8b7170'
    - '#8ea0a0'
    - '#9fd4c2'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
